<a href="https://colab.research.google.com/github/AdrNicole/DATA-ANALYTICS/blob/Modulo2_Programacion-con-Python-para-el-analisis-de-datos/D2_Clase5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio 1
Para desarrollar este desafío necesitarás los siguientes archivos:
`incidents.pkl`
`officers.pkl`
`subjects.pkl`

a. Carga los datos y crea un DataFrame con cada uno de ellos.

In [ ]:
import pickle
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.read_pickle("incidents.pkl")
df2 = pd.read_pickle("officers.pkl")
df3 = pd.read_pickle("subjects.pkl")

df1, df2, df3

(     case_number        date                  location subject_statuses  \
 0         44523A  2013-02-23     3000 Chihuahua Street          Injured
 1        121982X  2010-05-03  1300 N. Munger Boulevard          Injured
 2        605484T  2007-08-12   200 S. Stemmons Freeway            Other
 3        384832T  2007-05-26           7900 S. Loop 12   Shoot and Miss
 4        244659R  2006-04-03        6512 South Loop 12          Injured
 ..           ...         ...                       ...              ...
 214  161616-2016  2016-07-03   7440 Chesterfield Drive   Shoot and Miss
 215  141461-2016  2016-06-11         2700 Custer Drive   Shoot and Miss
 216  089985-2016  2016-04-16         4800 Columbia Ave   Shoot and Miss
 217  177645-2016  2016-07-23    1716 Chattanooga Place   Shoot and Miss
 218  165193-2016  2016-07-07           801 Main Street         Deceased

     subject_weapon                                           subjects  \
 0          Handgun                                   Curry, James L/M
 1          Handgun                                Chavez, Gabriel L/M
 2          Shotgun                                  Salinas, Nick L/M
 3          Unarmed  Smith, James B/M; Dews, Antonio B/M; Spearman,...
 4            Hands                                 Watkins, Caleb B/M
 ..             ...                                                ...
 214        Handgun                                  Brown, Desroy B/M
 215        Vehicle                                        Unknown B/M
 216        Handgun                                        Unknown L/M
 217        Handgun                                        Unknown B/M
 218  Assault Rifle                                 Johnson, Micah B/M

      subject_count                                           officers  \
 0                1          Patino, Michael L/M; Fillingim, Brian W/M
 1                1                               Padilla, Gilbert L/M
 2                1                                  Poston, Jerry W/M
 3                3                                 Mondy, Michael B/M
 4                1                             Armstrong, Michael W/M
 ..             ...                                                ...
 214              1                               Crenshaw, Joshua W/M
 215              1                                 Moore, Douglas B/M
 216              1                               Ruben, Fredirick W/M
 217              1                                   Rosen, Brett W/M
 218              1  Edwards, Henry W/M; Wells, Giovanni B/M; Junge...

      officer_count grand_jury_disposition attorney_general_forms_url  \
 0                2                No Bill                       None
 1                1                No Bill                       None
 2                1            See Summary                       None
 3                1                   None                       None
 4                1                No Bill                       None
 ..             ...                    ...                        ...
 214              1                   None                       None
 215              1                   None                       None
 216              1                   None                       None
 217              1                   None                       None
 218             12                   None                       None

                                            summary_url  \
 0    http://dallaspolice.net/reports/OIS/narrative/...
 1    http://dallaspolice.net/reports/OIS/narrative/...
 2    http://dallaspolice.net/reports/OIS/narrative/...
 3    http://dallaspolice.net/reports/OIS/narrative/...
 4    http://dallaspolice.net/reports/OIS/narrative/...
 ..                                                 ...
 214  http://dallaspolice.net/reports/OIS/narrative/...
 215  http://dallaspolice.net/reports/OIS/narrative/...
 216  http://dallaspolice.net/reports/OIS/narrative/...
 217                                               None
 218                                               None

                                           summary_text  latitude  longitude
 0    On Saturday, February 23, 2013, at approximate...       NaN        NaN
 1    On Monday, May 3, 2010, at approximately 8:06 ...       NaN        NaN
 2    On Sunday, August 12, 2007, at approximately 2...       NaN        NaN
 3    On Saturday, May 26, 2007, at approximately 1:...       NaN        NaN
 4    On Monday, April 3, 2006, at approximately 11:...       NaN        NaN
 ..                                                 ...       ...        ...
 214  7440 Chesterfield Drive 161616-2016\n\nOn July...  32.65628 -96.869793
 215  2700 Custer Drive 141461-2016\n\nOn June 11, 2...  32.70483 -96.779494
 216  4800 Columbia Avenue 089985-2016\n\nOn April 1...  32.79473 -96.764017
 217                                               None  32.81664 -96.851409
 218                                               None  32.77945 -96.804915

 [219 rows x 15 columns],
      case_number race gender  last_name  first_name           full_name
 0         44523A    L      M     Patino     Michael     Patino, Michael
 1         44523A    W      M  Fillingim       Brian    Fillingim, Brian
 2        121982X    L      M    Padilla     Gilbert    Padilla, Gilbert
 3        605484T    W      M     Poston       Jerry       Poston, Jerry
 4        384832T    B      M      Mondy     Michael      Mondy, Michael
 ..           ...  ...    ...        ...         ...                 ...
 365  165193-2016    W      M   Michaels        Mark      Michaels, Mark
 366  165193-2016    W      M  Borchardt      Jeremy   Borchardt, Jeremy
 367  165193-2016    W      M      Craig      Robert       Craig, Robert
 368  165193-2016    W      M     Cannon       Elmar       Cannon, Elmar
 369  165193-2016    B      M     Stuart  Kristopher  Stuart, Kristopher

 [370 rows x 6 columns],
      case_number race gender last_name first_name        full_name
 0         44523A    L      M     Curry      James     Curry, James
 1        121982X    L      M    Chavez    Gabriel  Chavez, Gabriel
 2        605484T    L      M   Salinas       Nick    Salinas, Nick
 3        384832T    B      M     Smith      James     Smith, James
 4        384832T    B      M      Dews    Antonio    Dews, Antonio
 ..           ...  ...    ...       ...        ...              ...
 218  161616-2016    B      M     Brown     Desroy    Brown, Desroy
 219  141461-2016    B      M   Unknown       None          Unknown
 220  089985-2016    L      M   Unknown       None          Unknown
 221  177645-2016    B      M   Unknown       None          Unknown
 222  165193-2016    B      M   Johnson      Micah   Johnson, Micah

 [223 rows x 6 columns])

b. Genera una tabla que contenga la unión de las 3 tablas. hint: utiliza sufijos para para las columnas que se llaman igual usando el parámetro suffixes de pd.merge().

In [ ]:
# Fusionar los DataFrames usando case_number" como clave de combinación
df1_df2 = pd.merge(df1, df2, on ='case_number', how = 'inner')
len(df1_df2) # 370
df1_df2_df3 = pd.merge(df1_df2, df3, on ='case_number', how = 'inner', suffixes = ('_df','_df3'))
df1_df2_df3.head(1)
len(df1_df2_df3) # 377

df1_df2_df3.head()

,case_number,date,location,subject_statuses,subject_weapon,subjects,subject_count,officers,officer_count,grand_jury_disposition,...,race_df,gender_df,last_name_df,first_name_df,full_name_df,race_df3,gender_df3,last_name_df3,first_name_df3,full_name_df3
0,44523A,2013-02-23,3000 Chihuahua Street,Injured,Handgun,"Curry, James L/M",1,"Patino, Michael L/M; Fillingim, Brian W/M",2,No Bill,...,L,M,Patino,Michael,"Patino, Michael",L,M,Curry,James,"Curry, James"
1,44523A,2013-02-23,3000 Chihuahua Street,Injured,Handgun,"Curry, James L/M",1,"Patino, Michael L/M; Fillingim, Brian W/M",2,No Bill,...,W,M,Fillingim,Brian,"Fillingim, Brian",L,M,Curry,James,"Curry, James"
2,121982X,2010-05-03,1300 N. Munger Boulevard,Injured,Handgun,"Chavez, Gabriel L/M",1,"Padilla, Gilbert L/M",1,No Bill,...,L,M,Padilla,Gilbert,"Padilla, Gilbert",L,M,Chavez,Gabriel,"Chavez, Gabriel"
3,605484T,2007-08-12,200 S. Stemmons Freeway,Other,Shotgun,"Salinas, Nick L/M",1,"Poston, Jerry W/M",1,See Summary,...,W,M,Poston,Jerry,"Poston, Jerry",L,M,Salinas,Nick,"Salinas, Nick"
4,384832T,2007-05-26,7900 S. Loop 12,Shoot and Miss,Unarmed,"Smith, James B/M; Dews, Antonio B/M; Spearman,...",3,"Mondy, Michael B/M",1,None,...,B,M,Mondy,Michael,"Mondy, Michael",B,M,Smith,James,"Smith, James"

c. Verifica si hay filas duplicadas; si es así, elimínalas.

In [ ]:
#from numpy._core.defchararray import count
df1_df2_df3_copia = df1_df2_df3.copy()
df1_df2_df3_copia.head(1)        # 377 rows con duplicados

# creo una nueva columna de boleanos siendo True = duplicados y False = No duplicado
df1_df2_df3_copia['duplicados'] = df1_df2_df3_copia.duplicated()
df1_df2_df3_copia[df1_df2_df3_copia.duplicated()]
len(df1_df2_df3_copia[df1_df2_df3_copia['duplicados']==False])  # como es 377 otra vez entonces no hubo duplicados

# a continuacion se muestran las filas sin duplicados
df1_df2_df3_copia[df1_df2_df3_copia['duplicados']==False].head()

,case_number,date,location,subject_statuses,subject_weapon,subjects,subject_count,officers,officer_count,grand_jury_disposition,...,gender_df,last_name_df,first_name_df,full_name_df,race_df3,gender_df3,last_name_df3,first_name_df3,full_name_df3,duplicados
0,44523A,2013-02-23,3000 Chihuahua Street,Injured,Handgun,"Curry, James L/M",1,"Patino, Michael L/M; Fillingim, Brian W/M",2,No Bill,...,M,Patino,Michael,"Patino, Michael",L,M,Curry,James,"Curry, James",False
1,44523A,2013-02-23,3000 Chihuahua Street,Injured,Handgun,"Curry, James L/M",1,"Patino, Michael L/M; Fillingim, Brian W/M",2,No Bill,...,M,Fillingim,Brian,"Fillingim, Brian",L,M,Curry,James,"Curry, James",False
2,121982X,2010-05-03,1300 N. Munger Boulevard,Injured,Handgun,"Chavez, Gabriel L/M",1,"Padilla, Gilbert L/M",1,No Bill,...,M,Padilla,Gilbert,"Padilla, Gilbert",L,M,Chavez,Gabriel,"Chavez, Gabriel",False
3,605484T,2007-08-12,200 S. Stemmons Freeway,Other,Shotgun,"Salinas, Nick L/M",1,"Poston, Jerry W/M",1,See Summary,...,M,Poston,Jerry,"Poston, Jerry",L,M,Salinas,Nick,"Salinas, Nick",False
4,384832T,2007-05-26,7900 S. Loop 12,Shoot and Miss,Unarmed,"Smith, James B/M; Dews, Antonio B/M; Spearman,...",3,"Mondy, Michael B/M",1,None,...,M,Mondy,Michael,"Mondy, Michael",B,M,Smith,James,"Smith, James",False


d. ¿Cuántos sujetos de género F hay en el DataFrame resultante? hint: usa el método
.value_counts() sobre la columna.

In [ ]:
# sujetos -> df3
df1_df2_df3_copia['gender_df3'].value_counts()
# 9 sujetos con el genero F

gender_df3
M    368
F      9
Name: count, dtype: int64

e. ¿En cuántos números de caso hay por lo menos una sospechosa que sea mujer? hint:
utiliza el método unique() para obtener los valores únicos de una columna específica de un DataFrame luego de filtrar.

In [ ]:
df4 = pd.merge(df1,df2, on= 'case_number',how='inner')
df4_casos_gender = pd.concat([df4['case_number'], df4['gender']],axis=1)
# filtrar < extraer < contar
df4_casos_gender_F = df4_casos_gender[df4['gender']=='F']
df4_casos_gender_F_unico = df4_casos_gender_F['case_number'].unique()
resp = len(df4_casos_gender_F_unico)
print(f'hay {resp} casos donde por lo menos hay una sospechosa mujer')

hay 17 casos donde por lo menos hay una sospechosa mujer

f. Genera una tabla pivote que muestre en las filas el género del oficial y en las columnas el género del subject. ¿Cómo interpretas los valores que muestra esta vista?

A continuacion se muestra lo siguiente:
- las mujeres oficiales son las que atienden el menor numero de casos cometidos por sujetos mujeres (2 case_number).
- las mujeres oficiales son las que atienden poco mas de casos cometidos por hombres (18 case_number).
- los hombres oficiales son los que atienden más casos cometidos por sujetos hombres (350 case_number).
- los hombres oficales atienden menos casos cuando son cometidos por sujetos mujeres (7 case_number).

En general hay una mayor participacion de hombres tanto de oficiales que atienden el caso como los sujetos que los cometen; mientras que en el caso de las mujeres su participación es notablemente limitada en este ámbito.

In [ ]:
tabla_pivote = pd.pivot_table(
    df1_df2_df3_copia,
    values = 'case_number',
    index= 'gender_df',
    columns= 'gender_df3',
    aggfunc= 'count'
)

tabla_pivote

gender_df3  F    M
gender_df
F           2   18
M           7  350

# Ejercicio 2
Para continuar con el desarrollo de este desafío, necesitarás el archivo
`Cleaned_DS_Jobs.csv`

a. Carga los datos y crea un DataFrame con ellos.

In [ ]:
df5 = pd.read_csv('Cleaned_DS_Jobs.csv')
df5

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,company_age,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,27,0,0,0,0,1,0,0,data scientist,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,52,0,0,1,0,0,0,1,data scientist,na
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,Private Practice / Firm,Consulting,...,39,1,1,0,0,1,0,0,data scientist,na
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,Company - Public,Electrical & Electronic Manufacturing,...,20,1,1,0,0,1,0,0,data scientist,na
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,22,1,1,0,0,0,0,0,data scientist,na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,Data Scientist,105-167,Summary\n\nWe’re looking for a data scientist ...,3.6,TRANZACT,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,Company - Private,Advertising & Marketing,...,31,1,1,1,0,0,1,1,data scientist,na
656,Data Scientist,105-167,Job Description\nBecome a thought leader withi...,0.0,JKGT,"San Francisco, CA",-1,-1,-1,-1,...,-1,0,0,0,0,0,0,0,data scientist,na
657,Data Scientist,105-167,Join a thriving company that is changing the w...,0.0,AccessHope,"Irwindale, CA",-1,-1,-1,-1,...,-1,1,1,1,0,0,1,0,data scientist,na
658,Data Scientist,105-167,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,Company - Private,Advertising & Marketing,...,-1,1,0,1,1,0,0,1,data scientist,na
659,Data Scientist,105-167,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers,"New York, NY","Carle Place, NY",1001 to 5000 employees,Company - Public,Wholesale,...,44,1,1,0,0,0,1,0,data scientist,na

b. Utiliza la siguiente lista de valores que serán considerados como nulos:
["na", "NA",-1, "0", "-1", "null", "n/a", "N/A", "NULL"]
(hint: utiliza el método replace para reemplazar los valores indicados por np.nan)

In [ ]:
# Reemplazar inf y -inf por NaN manualmente
df5.replace(["na", "NA",-1, "0", "-1", "null", "n/a", "N/A", "NULL"], np.nan, inplace=True)
df5

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,company_age,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,27.0,0,0,0,0,1,0,0,data scientist,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,52.0,0,0,1,0,0,0,1,data scientist,NaN
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,Private Practice / Firm,Consulting,...,39.0,1,1,0,0,1,0,0,data scientist,NaN
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,Company - Public,Electrical & Electronic Manufacturing,...,20.0,1,1,0,0,1,0,0,data scientist,NaN
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,22.0,1,1,0,0,0,0,0,data scientist,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,Data Scientist,105-167,Summary\n\nWe’re looking for a data scientist ...,3.6,TRANZACT,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,Company - Private,Advertising & Marketing,...,31.0,1,1,1,0,0,1,1,data scientist,NaN
656,Data Scientist,105-167,Job Description\nBecome a thought leader withi...,0.0,JKGT,"San Francisco, CA",NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,0,data scientist,NaN
657,Data Scientist,105-167,Join a thriving company that is changing the w...,0.0,AccessHope,"Irwindale, CA",NaN,NaN,NaN,NaN,...,NaN,1,1,1,0,0,1,0,data scientist,NaN
658,Data Scientist,105-167,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,Company - Private,Advertising & Marketing,...,NaN,1,0,1,1,0,0,1,data scientist,NaN
659,Data Scientist,105-167,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers,"New York, NY","Carle Place, NY",1001 to 5000 employees,Company - Public,Wholesale,...,44.0,1,1,0,0,0,1,0,data scientist,NaN

c. Elimina todas las filas con datos faltantes. (hint: utiliza el método .dropna())

In [ ]:
# Copia para eliminar filas con valores faltantes
df_sin_filas_na = df5.copy().dropna()

df_sin_filas_na.head(3)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,company_age,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,27.0,0,0,0,0,1,0,0,data scientist,senior
32,Senior Research Statistician- Data Scientist,75-131,Acuity is seeking a Senior Research Statistici...,4.8,Acuity Insurance,"Sheboygan, WI","Sheboygan, WI",1001 to 5000 employees,Company - Private,Insurance Carriers,...,95.0,0,0,0,0,0,0,0,data scientist,senior
38,Senior Analyst/Data Scientist,75-131,At Edmunds were driven to make car buying easi...,3.4,Edmunds.com,"Santa Monica, CA","Santa Monica, CA",501 to 1000 employees,Company - Private,Internet,...,54.0,1,1,0,0,1,1,0,data scientist,senior


d. Apartir de la columna “Salary Estimate”, genera dos columnas: Salario Estimado Mínimo y Máximo. (hint: Utiliza el método apply sobre la columna.)

In [ ]:
df_sin_filas_na[['Salario_Estimado_Min','Salario_Estimado_Max']] = df_sin_filas_na['Salary Estimate'].apply(lambda w: pd.Series(str(w).split('-')))
df_sin_filas_na.head(3)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority,Salario_Estimado_Min,Salario_Estimado_Max
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,0,0,0,1,0,0,data scientist,senior,137,171
32,Senior Research Statistician- Data Scientist,75-131,Acuity is seeking a Senior Research Statistici...,4.8,Acuity Insurance,"Sheboygan, WI","Sheboygan, WI",1001 to 5000 employees,Company - Private,Insurance Carriers,...,0,0,0,0,0,0,data scientist,senior,75,131
38,Senior Analyst/Data Scientist,75-131,At Edmunds were driven to make car buying easi...,3.4,Edmunds.com,"Santa Monica, CA","Santa Monica, CA",501 to 1000 employees,Company - Private,Internet,...,1,0,0,1,1,0,data scientist,senior,75,131

e. Realiza la recodificación de la columna Size con los valores de la siguiente tabla: (hint: utilice reemplazo con diccionario usando el método replace sobre la columna.)

In [ ]:
df_sin_filas_na.replace(['10000+ employees','5001 to 10000 employees','1001 to 5000 employees','201 to 500 employees','51 to 200 employees','501 to 1000 employees','Unknown'],['MegaEmpresas','Grandes Empresas','Medianas Empresas','Pequeñas Empresas','Pequeñas Grandes Empresas','Microempresas','Empresas sin Información'], inplace=True)
df_sin_filas_na.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,hadoop,spark,aws,tableau,big_data,job_simp,seniority,Salario_Estimado_Min,Salario_Estimado_Max,Salario_Estimado_Minimo
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",Medianas Empresas,Nonprofit Organization,Insurance Carriers,...,0,0,1,0,0,data scientist,senior,137,171.0,137.0
32,Senior Research Statistician- Data Scientist,75-131,Acuity is seeking a Senior Research Statistici...,4.8,Acuity Insurance,"Sheboygan, WI","Sheboygan, WI",Medianas Empresas,Company - Private,Insurance Carriers,...,0,0,0,0,0,data scientist,senior,75,131.0,75.0
38,Senior Analyst/Data Scientist,75-131,At Edmunds were driven to make car buying easi...,3.4,Edmunds.com,"Santa Monica, CA","Santa Monica, CA",Microempresas,Company - Private,Internet,...,0,0,1,1,0,data scientist,senior,75,131.0,75.0
45,Senior Data Scientist,75-131,Klaviyo is looking for Senior Data Scientists ...,4.8,Klaviyo,"Boston, MA","Boston, MA",Pequeñas Empresas,Company - Private,Computer Hardware & Software,...,0,0,0,0,0,data scientist,senior,75,131.0,75.0
54,Senior Data Scientist,75-131,Benson Hill empowers innovators to develop mor...,3.5,Benson Hill,"Saint Louis, MO","Saint Louis, MO",Pequeñas Empresas,Company - Private,Biotech & Pharmaceuticals,...,0,0,0,0,1,data scientist,senior,75,131.0,75.0

f. Finalmente, genera una tabla pivote que muestre la media del salario estimado mínimo y
la media del salario estimado máximo por tamaño de empresa. (hint: utiliza
pd.pivot_table para generar la vista adecuada con las columnas generadas.)

In [ ]:
#(df_sin_filas_na['Salario_Estimado_Max'], df_sin_filas_na['Salario_Estimado_Min'])

df_sin_filas_na['Salario_Estimado_Minimo']= df_sin_filas_na['Salario_Estimado_Min'].fillna(0).apply(lambda w: int(w))
df_sin_filas_na['Salario_Estimado_Maximo']=df_sin_filas_na['Salario_Estimado_Max'].apply(lambda w: int(w))
df_sin_filas_na

tabla_pivote2 = pd.pivot_table(
    df_sin_filas_na,
    values = ['Salario_Estimado_Minimo','Salario_Estimado_Maximo'],
    index= 'Size',
    #columns= ,
    aggfunc= 'mean'
)
tabla_pivote2.round(2)

                           Salario_Estimado_Maximo  Salario_Estimado_Minimo
Size
Empresas sin Información                    110.50                    73.00
Grandes Empresas                            138.88                    92.12
Medianas Empresas                           137.46                    93.92
MegaEmpresas                                151.11                    97.89
Microempresas                               146.24                   100.18
Pequeñas Empresas                           141.14                    93.57
Pequeñas Grandes Empresas                   137.67                   100.67