<a href="https://colab.research.google.com/github/AdrNicole/DATA-ANALYTICS/blob/Modulo2_Programacion-con-Python-para-el-analisis-de-datos/D4_Clase4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Desafío 4
Para desarrollar este desafío necesitarás el archivo

> `resumen_resultados_astronautas.csv`

El IMC es una medida importante que nos ayuda a determinar si una persona
tiene un peso saludable para poder ser un astronauta. Para calcularlo se utiliza la
fórmula `IMC = m / h*h`

Donde m corresponde al peso del astronauta en kilogramos, y h su estatura en metros
El rendimiento en las diferentes evaluaciones permitirá también aceptar o rechazar a los
postulantes.

1. Crea un DataFrame con el archivo entregado.

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('resumen_resultados_astronautas.csv')
df.head()
#df.info()
#df.describe() # genera medidas como count, mean, std, min, 25%, 50%, 75% y max

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica
0,Alana Morillo,32,75,180,93,88,78,89,6,Si
1,Fátima Tafalla,27,68,167,82,95,81,87,4,Si
2,Sofía Puig,29,80,185,85,80,90,91,3,Si
3,Valentina Tasis,30,65,175,90,91,85,92,2,No
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si

2. Crea la columna "IMC" usando la fórmula entregada.

In [ ]:
# corregimos la altura que está en centímetros, y digo esto porque ninguna persona tiene 180 metros de altura.
df['altura_corregida'] = df['altura']/100

# ahora si, calculo IMC
IMC = df['peso']/(df['altura_corregida']*df['altura_corregida'])
df
df['IMC'] = IMC
df.head()

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones,altura_corregida
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,23.148148,87.00,1.80
1,Fátima Tafalla,27,68,167,82,95,81,87,4,Si,24.382373,86.25,1.67
2,Sofía Puig,29,80,185,85,80,90,91,3,Si,23.374726,86.50,1.85
3,Valentina Tasis,30,65,175,90,91,85,92,2,No,21.224490,89.50,1.75
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si,22.694019,87.25,1.83

3.1 Crea la columna "promedio_evaluaciones" con el promedio de las 4 columnas
de evaluaciones.

In [ ]:
# creacion de tabla evaluaciones
evaluaciones = df.iloc[:,4:8]
evaluaciones.head()
  # Forma1 (loc): sumar columnas por nombres
suma1 = evaluaciones['evaluacion_fisica']+ evaluaciones['evaluacion_psicologica']+ evaluaciones['evaluacion_adaptativa']+ evaluaciones['evaluacion_medica']
evaluaciones['suma1']=suma1
evaluaciones.head()
  # Forma2 (iloc): sumar columnas por su indice
evaluaciones.iloc[:3] # <- fila
evaluaciones.iloc[:,1] # <- columna
suma2 = evaluaciones.iloc[:,0] + evaluaciones.iloc[:,1] + evaluaciones.iloc[:,2] + evaluaciones.iloc[:,3]
evaluaciones['suma2']=suma2
evaluaciones.head()
  # incorporar la columna 'promedio= suma2/4' a la tabla principal df
df['promedio_evaluaciones'] = suma2/4
df.head()

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones,altura_corregida,IMC_adecuado
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,23.148148,87.00,1.80,True
1,Fátima Tafalla,27,68,167,82,95,81,87,4,Si,24.382373,86.25,1.67,True
2,Sofía Puig,29,80,185,85,80,90,91,3,Si,23.374726,86.50,1.85,True
3,Valentina Tasis,30,65,175,90,91,85,92,2,No,21.224490,89.50,1.75,True
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si,22.694019,87.25,1.83,True

3.1.   Si el IMC está entre 18.5 y 24.9, entonces el candidato
tendrá un IMC adecuado para ser astronauta. Filtra el DataFrame para
obtener solo aquellas filas donde el IMC esté dentro de los límites
entregados.

In [ ]:
df_IMC_Adecuado = df
IMC_adecuado= df_IMC_Adecuado[np.logical_and(df['IMC']>=18.5,df['IMC']<=24.9)]
#(df['IMC']>=18.5) & (df['IMC']<=24.9)
len(IMC_adecuado)
IMC_adecuado.tail(6) # verificamos, que la fila 26 en la tabla df es False y este filtro quita esa fila, por tanto este filtro es correcto

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones,altura_corregida,IMC_adecuado
25,Leonardo Magrina,39,65,171,79,92,90,85,8,No,22.229062,86.50,1.71,True
27,Sophie González,36,75,176,85,82,84,80,7,No,24.212293,82.75,1.76,True
28,Alexia Gaos,21,69,169,93,94,93,86,0,Si,24.158818,91.50,1.69,True
29,Fátima Varela,33,73,182,91,90,91,88,5,Si,22.038401,90.00,1.82,True
30,Clara Arias,44,63,162,77,87,88,84,11,No,24.005487,84.00,1.62,True
31,Paloma Berganza,28,62,174,87,85,87,78,3,Si,20.478267,84.25,1.74,True

4. El promedio de las 4 evaluaciones debe ser mayor o igual a 87. Filtra el
DataFrame resultante y agrega esta condición al filtro aplicado en el paso
anterior.

In [ ]:
IMC_adecuado_evalu87 = IMC_adecuado[np.logical_or(IMC_adecuado['promedio_evaluaciones']>87, IMC_adecuado['promedio_evaluaciones']==87)]
IMC_adecuado_evalu87.head()

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones,altura_corregida,IMC_adecuado
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,23.148148,87.00,1.80,True
3,Valentina Tasis,30,65,175,90,91,85,92,2,No,21.224490,89.50,1.75,True
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si,22.694019,87.25,1.83,True
6,María Juderías,28,78,182,88,85,87,92,5,Si,23.547881,88.00,1.82,True
8,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,21.785876,89.75,1.88,True

6. Modifica el valor de la columna "califica", para que diga "Si" en todas las filas del
DataFrame resultante.

In [ ]:
IMC_adecuado_evalu87['califica']='Si'
IMC_adecuado_evalu87

/tmp/ipykernel_2559/673268054.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMC_adecuado_evalu87['califica']='Si'

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones,altura_corregida,IMC_adecuado
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,23.148148,87.00,1.80,True
3,Valentina Tasis,30,65,175,90,91,85,92,2,Si,21.224490,89.50,1.75,True
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si,22.694019,87.25,1.83,True
6,María Juderías,28,78,182,88,85,87,92,5,Si,23.547881,88.00,1.82,True
8,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,21.785876,89.75,1.88,True
12,Patricio Encarnación,30,81,190,93,86,88,91,4,Si,22.437673,89.50,1.90,True
13,Cristóbal Miralles,31,72,174,88,91,86,92,6,Si,23.781213,89.25,1.74,True
16,Nicolás Cambeiro,29,68,175,88,90,81,90,2,Si,22.204082,87.25,1.75,True
18,Samuel Gálvez,22,74,183,91,91,91,86,3,Si,22.096808,89.75,1.83,True
23,Christopher Berganza,23,70,173,92,93,92,85,1,Si,23.388687,90.50,1.73,True
28,Alexia Gaos,21,69,169,93,94,93,86,0,Si,24.158818,91.50,1.69,True
29,Fátima Varela,33,73,182,91,90,91,88,5,Si,22.038401,90.00,1.82,True

7. Exporta el DataFrame resultante a un archivo .csv separado por comas con el
nombre "astronautas_calificados.csv".

In [ ]:
IMC_adecuado_evalu87.to_excel("df_filtrado_sin_indice.xlsx", index=False)